### ISSUE TITLE
False premise

### ISSUE THREAD

**Issue by danielchatfield** [yocontra/are-you-a-cop#1]
> Around the world there is one universal constant: If you ask a cop if they are a cop, they have to tell you.

This is not true in the UK (source: training to be a special constable)

**Comment by danielchatfield** [comment]
Doesn't look like it is true in America either: http://www.snopes.com/risque/hookers/cop.asp

**Comment by yocontra** [comment]
This is a joke module, making fun of people who think that this is true. The level of sarcasm in the README might be too low, I will take a PR to make it more obvious.

**Comment by junosuarez** [comment]
@contra, dude, never break character! -1, dude, -1

**Comment by kid-icarus** [comment]
srsly man :-1:  :-1:  :-1:  :-1:  :-1:

**Comment by danielchatfield** [comment]
My joke-meter is clearly broken. If I'd read the readme fully (and actually
seen what it was doing) then it would have been clear that this was not
serious.

On Tuesday, 29 July 2014, Ryan Kois notifications@github.com wrote:

> srsly man [image: :-1:][image: :-1:][image: :-1:][image: :-1:][image:
> :-1:]
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/contra/are-you-a-cop/issues/1#issuecomment-50420199.

## 

For contact info visit: www.danielchatfield.com
