### ISSUE TITLE
please add "are you a snitch" support

### ISSUE THREAD

**Issue by alvint** [yocontra/are-you-a-cop#6]
Can you please add "are you a snitch" support as well?

**Comment by talon** [comment]
Snitches don't have to tell you what they are. I met a guy once who I am pretty sure was a snitch, but when I asked he said he wasn't. I think he was lying. Why wouldn't he?

-1 Unsustainable and breaks Do One Thing Well philosophy.

**Comment by yocontra** [comment]
No way to enforce this, since only cops have to tell you who they are

**Comment by alvint** [comment]
What about the Freedom of Information act? If you submit a request the government has to tell you who's snitching on you, right?
