### ISSUE TITLE
undercover cops

### ISSUE THREAD

**Issue by ORESoftware** [yocontra/are-you-a-cop#7]
https://www.erowid.org/freedom/police/police_info6.shtml

Police don't have to reveal identity if they are undercover, or not.

;)

**Comment by yocontra** [comment]
ya they do

**Comment by ORESoftware** [comment]
what about FBI/CIA

CIA, definitely not, but they are all abroad

**Comment by yocontra** [comment]
ya even CIA, Mossad, KGB, NSA, ISIS, etc.

**Comment by SlexAxton** [comment]
my dad said that they do

**Comment by ORESoftware** [comment]
ISIS 4 sure
